apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-app.fullname" . }}
  labels:
    {{- include "base-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "base-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
