apiVersion: v1
kind: Secret
metadata:
  name: repo-platform-infra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/erikkvale/platform-eng-infra.git
